---
# Per environment values which override defaults in hmpps-community-support-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: community-support-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    SERVICES_HMPPS_AUTH_API_BASE_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    SERVICES_MANAGE_USERS_API_BASE_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    SERVICES_NDELIUS_INTEGRATION_API_BASE_URL: "https://probation-offender-search-dev.hmpps.service.justice.gov.uk"
    SERVICES_NOMIS_API_BASE_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
    LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_REACTIVE_FUNCTION_CLIENT: DEBUG
    LOGGING_LEVEL_REACTOR_NETTY_HTTP_CLIENT: DEBUG

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-community-support-dev
