name: SchemaSpy report

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      java_options:
        type: string
        default: '-Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=true -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.workers.max=1'
        required: false
        description: Setting up common java options


jobs:
  database_report:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Generate Database Schema Report
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Start Required Services
        run: docker compose up hmpps-auth auth-db postgresql localstack -d
      - name: Initialise DB
        shell: bash
        run: |
          export JAVA_OPTS="${{ inputs.java_options }}"
           ./gradlew initialiseDatabase
      - uses: ministryofjustice/hmpps-github-actions/.github/actions/database_schema_report@v2 # WORKFLOW_VERSION
        with:
          database_name: postgres
          schema: public
          user: admin
          password: admin_password
